[tool]
[tool.poetry]
name = "SakirUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy SakirUserBot to Heroku"
authors = ["SakieUserBot"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
